### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by bbkarabulut** [limanmys/zabbix-cleaner-go#1]
/var/log/zabbix-db-cleaner# tail -f cleaner.log

2022/11/07 09:20:43 main.go:18: error when deleting trends_uint data err:strconv.Atoi: parsing "60;": invalid syntax
2022/11/08 09:20:43 main.go:18: error when deleting events data err:strconv.Atoi: parsing "60;": invalid syntax
2022/11/08 09:20:43 main.go:18: error when deleting history data err:strconv.Atoi: parsing "60;": invalid syntax
2022/11/08 09:20:44 main.go:18: error when deleting history_uint data err:strconv.Atoi: parsing "60;": invalid syntax
2022/11/08 09:20:44 main.go:18: error when deleting history_str data err:strconv.Atoi: parsing "60;": invalid syntax
2022/11/08 09:20:44 main.go:18: error when deleting history_text data err:strconv.Atoi: parsing "60;": invalid syntax
2022/11/08 09:20:44 main.go:18: error when deleting auditlog data err:strconv.Atoi: parsing "60;": invalid syntax
2022/11/08 09:20:44 main.go:18: error when deleting acknowledges data err:strconv.Atoi: parsing "60;": invalid syntax
2022/11/08 09:20:44 main.go:18: error when deleting trends data err:strconv.Atoi: parsing "60;": invalid syntax
2022/11/08 09:20:44 main.go:18: error when deleting trends_uint data err:strconv.Atoi: parsing "60;": invalid syntax

**Comment by zekiahmetbayar** [comment]
Selamlar, 

.env dosyasındaki 

`INTERVAL=60;` olarak belirlediğiniz değeri

`INTERVAL=60` olarak değiştirirseniz sorun çözülecektir.
